# Generated by Django 6.0.3 on 2026-03-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PROJECT_OWNER', 'Project Owner'), ('EMPLOYEE', 'Employee'), ('CLIENT', 'Client')], default='CLIENT', max_length=30),
        ),
    ]
