# Generated by Django 6.0.3 on 2026-04-01 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0001_initial"),
        ("ticket_messages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="message",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="ticket_messages.ticketmessage",
            ),
        ),
    ]
